type ItemsServicesList = {
    uid: string,
    code: string,
    name: string,
    brand_uid: string,
    brand_name: string,
    item_category_uid: string,
    item_category_name: string,
    unit_uid: string,
    unit_name: string,
    min_qty: number,
    part_number: string,
    interchange_part?: string | null,
    image: string,
    movement_category_uid: string,
    movement_category_name: string,
    valuation_method_uid: string,
    valuation_method_name: string,
    material_group_uid: string,
    material_group_name: string,
    sub_material_group_uid: string,
    sub_material_group_name: string,
    supplier_uid: string,
    supplier_name: string,
    price?: string,
    additional_info?: string
}

type ItemsServicesForm = {
    code: string,
    name: string,
    brand_uid: string,
    item_category_uid: string,
    unit_uid: string,
    min_qty: number,
    part_number: string,
    interchange_part?: string | null,
    image: string,
    movement_category_uid: string,
    valuation_method_uid: string,
    material_group_uid: string,
    sub_material_group_uid: string,
    supplier_uid: string,
    price?: string | null,
    additional_info?: string | null
}