type ItemsList = {
    uid: string,
    code: string,
    name: string,
    brand: { uid: string, name: string } | null,
    category: { uid: string, name: string } | null,
    unit: { uid: string, symbol: string, name: string } | null,
    min_qty: number,
    part_number: string,
    interchange_part?: string,
    image?: string | File | File[] | undefined,
    movement_category: { uid: string, name: string } | null,
    valuation_method: { uid: string, name: string } | null,
    material_group: { uid: string, code: string, name: string } | null,
    sub_material_group: { uid: string, code: string, name: string } | null,
    supplier: { uid: string, name: string } | null,
    request_types: { uid: string, name: string }[] | null,
    unit_types: { uid: string, name: string }[] | null,
    price?: string,
    exp_date?: Date,
    additional_info?: string,
    created_at: string,
    updated_at: string
    created_by_name: string,
    updated_by_name: string
}

type ItemsForm = {
    name: string,
    brand_uid: string | null,
    category_uid: string | null,
    unit_uid: string | null,
    movement_category_uid: string | null,
    valuation_method_uid: string | null,
    material_group_uid: string | null,
    sub_material_group_uid: string | null,
    supplier_uid: string | null,
    request_types_uid: string[] | null,
    unit_types_uid: string[] | null,
    min_qty: number,
    part_number: string,
    interchange_part?: string,
    image?: string | File | File[] | undefined,
    price?: string,
    exp_date?: Date | null,
    additional_info?: string,
    // Initial stock (optional)
    stock_warehouse_uid?: string | null,
    stock_rack_uid?: string | null,
    stock_tank_uid?: string | null,
    stock_qty?: number | null,
}