import 'vuetify/styles'
import { createVuetify } from 'vuetify'
import { aliases } from 'vuetify/iconsets/mdi-svg'
import colors from 'vuetify/util/colors'
import MaterialSymbolsCheckBoxRounded from '~icons/material-symbols/check-box-rounded'
import MaterialSymbolsCheckBoxOutlineBlank from '~icons/material-symbols/check-box-outline-blank'
import MaterialSymbolsKeyboardArrowUpRounded from '~icons/material-symbols/keyboard-arrow-up-rounded'
import MaterialSymbolsKeyboardArrowDownRounded from '~icons/material-symbols/keyboard-arrow-down-rounded'
// import FaSolidSortUp from '~icons/fa-solid/sort-up'
// import FaSolidSortDown from '~icons/fa-solid/sort-down'
import {
    VApp,
    VAppBar,
    VToolbar,
    VToolbarTitle,
    VToolbarItems,
    VBreadcrumbs,
    VNavigationDrawer,
    VMain,
    VFooter,
    VResponsive,
    VContainer,
    VSheet,
    VOverlay,
    VHover,
    VSnackbarQueue,
    VRow,
    VCol,
    VDialog,
    VCard,
    VCardTitle,
    VCardSubtitle,
    VCardText,
    VCardActions,
    VCardItem,
    VExpandTransition,
    VDivider,
    VTabs,
    VTab,
    VTabsWindow,
    VTabsWindowItem,
    VStepper,
    VStepperHeader,
    VStepperItem,
    VStepperWindow,
    VStepperWindowItem,
    VStepperActions,
    VList,
    VListItem,
    VListItemTitle,
    VTable,
    VDataTable,
    VDataTableServer,
    VDataTableVirtual,
    VPagination,
    VForm,
    VTextField,
    VNumberInput,
    VFileInput,
    VTextarea,
    VSelect,
    VAutocomplete,
    VBtn,
    VBtnToggle,
    VSwitch,
    VCheckbox,
    VRadioGroup,
    VRadio,
    VDatePicker,
    VIcon,
    VMenu,
    VSpacer,
    VImg,
    VChip,
    VBadge,
    VAlert,
    VTimeline,
    VTimelineItem,
    VTooltip,
    VProgressCircular,
    VProgressLinear,
} from 'vuetify/components'
import { VFileUpload, VFileUploadItem } from 'vuetify/labs/components'

export const vuetify = createVuetify({
    components: {
        VApp,
        VAppBar,
        VToolbar,
        VToolbarTitle,
        VToolbarItems,
        VBreadcrumbs,
        VNavigationDrawer,
        VMain,
        VFooter,
        VResponsive,
        VContainer,
        VSheet,
        VOverlay,
        VHover,
        VSnackbarQueue,
        VRow,
        VCol,
        VDialog,
        VCard,
        VCardTitle,
        VCardSubtitle,
        VCardText,
        VCardActions,
    VCardItem,
    VExpandTransition,
        VDivider,
        VTabs,
        VTab,
        VTabsWindow,
        VTabsWindowItem,
        VStepper,
        VStepperHeader,
        VStepperItem,
        VStepperWindow,
        VStepperWindowItem,
        VStepperActions,
        VList,
        VListItem,
        VListItemTitle,
        VTable,
        VDataTable,
        VDataTableServer,
        VDataTableVirtual,
        VPagination,
        VForm,
        VTextField,
        VNumberInput,
        VFileInput,
        VTextarea,
        VSelect,
        VAutocomplete,
        VBtn,
        VBtnToggle,
        VSwitch,
        VCheckbox,
        VRadioGroup,
        VRadio,
        VDatePicker,
        VIcon,
        VMenu,
        VSpacer,
        VImg,
        VChip,
        VBadge,
        VAlert,
        VTimeline,
        VTimelineItem,
        VTooltip,
        VProgressCircular,
        VProgressLinear,
        VFileUpload,
        VFileUploadItem
    },
    icons: {
        defaultSet: 'mdi',
        aliases: {
            ...aliases,
            collapse: MaterialSymbolsKeyboardArrowUpRounded,
            expand: MaterialSymbolsKeyboardArrowDownRounded,
            checkboxOn: MaterialSymbolsCheckBoxRounded,
            checkboxOff: MaterialSymbolsCheckBoxOutlineBlank
        }
    },
    theme: {
        defaultTheme: 'dark',
        
        themes: {
            light: {
                dark: false,
                colors: {
                    primary: colors.blue.accent2,
                    success: colors.green.darken1,
                    warning: colors.yellow.darken2,
                    error: colors.red.darken1
                }
            },
            dark: {
                dark: true,
                colors: {
                    primary: colors.blue.accent2,
                    success: colors.green.darken1,
                    warning: colors.amber.darken1,
                    error: colors.red.darken1
                }
            }
        }
    }
})